# Creado con Kata Kuntur - Modelador de Datos
# sitio web: http://katakuntur.llullutuqo.me/
# Si usted encuentra algun error le agradeceriamos que lo comunique a me@llullutuqo.me

# GENERANDO TABLAS
CREATE TABLE ANUNCIO (
	id integer NOT NULL,
	nombre varchar(25) NOT NULL,
	inicio date NOT NULL,
	final date NOT NULL,
	status varchar(10) NOT NULL,
	categoria_id INTEGER NOT NULL,
	KEY(categoria_id),
	establecimiento_id INTEGER NOT NULL,
	KEY(establecimiento_id),
	historial_anuncios_id INTEGER NOT NULL,
	KEY(historial_anuncios_id),
	PRIMARY KEY(id)
)ENGINE=INNODB;
CREATE TABLE CATEGORIA (
	id integer NOT NULL,
	nombre varchar(50) NOT NULL,
	PRIMARY KEY(id)
)ENGINE=INNODB;
CREATE TABLE ESTABLECIMIENTO (
	id INTEGER NOT NULL,
	nombre varchar(50) NOT NULL,
	direccion varchar(80) NOT NULL,
	geo_latitud varchar(20) NOT NULL,
	geo_longitud varchar(20) NOT NULL,
	calificacion double NOT NULL,
	categoria_id INTEGER NOT NULL,
	KEY(categoria_id),
	usuario_id INTEGER NOT NULL,
	KEY(usuario_id),
	PRIMARY KEY(id)
)ENGINE=INNODB;
CREATE TABLE PLATILLO (
	id INTEGER NOT NULL,
	nombre varchar(30) NOT NULL,
	tiempoprepara INTEGER NOT NULL,
	calificacion double NOT NULL,
	precioaprox double NOT NULL,
	categoria_id INTEGER NOT NULL,
	KEY(categoria_id),
	establecimiento_id INTEGER NOT NULL,
	KEY(establecimiento_id),
	PRIMARY KEY(id)
)ENGINE=INNODB;
CREATE TABLE RESEnA (
	id INTEGER NOT NULL,
	contenido varchar(100) NOT NULL,
	fecha DATE NOT NULL,
	calificacion double NOT NULL,
	platillo_id INTEGER NOT NULL,
	KEY(platillo_id),
	usuario_final_id INTEGER NOT NULL,
	KEY(usuario_final_id),
	PRIMARY KEY(id)
)ENGINE=INNODB;
CREATE TABLE HISTORIAL_ANUNCIOS (
	id integer NOT NULL,
	fechapeticion DATE NOT NULL,
	statuspublica varchar(10) NOT NULL,
	statuspago varchar(10) NOT NULL,
	fechapago date NOT NULL,
	monto DOUBLE NOT NULL,
	tipopago varchar(15) NOT NULL,
	cuenta varchar(6) NOT NULL,
	banco varchar(20) NOT NULL,
	establecimiento_id INTEGER NOT NULL,
	KEY(establecimiento_id),
	PRIMARY KEY(id)
)ENGINE=INNODB;
CREATE TABLE TENDENCIAS (
	id INTEGER NOT NULL,
	nombre varchar(25) NOT NULL,
	busquedas integer NOT NULL,
	ultimaact date NOT NULL,
	categoria_id INTEGER NOT NULL,
	KEY(categoria_id),
	PRIMARY KEY(id)
)ENGINE=INNODB;
CREATE TABLE USUARIO (
	id INTEGER NOT NULL,
	username varchar(10) NOT NULL,
	pass varchar(15) NOT NULL,
	fechainicio DATE NOT NULL,
	tipo integer NOT NULL,
	PRIMARY KEY(id)
)ENGINE=INNODB;
CREATE TABLE USUARIO_FINAL (
	id integer NOT NULL,
	confiabilidad DOUBLE NOT NULL,
	usuario_id INTEGER NOT NULL,
	KEY(usuario_id),
	PRIMARY KEY(id)
)ENGINE=INNODB;
CREATE TABLE FAVORITOS (
	categoria integer NULL,
	establecimiento integer NULL,
	usuario_final_id INTEGER NOT NULL,
	KEY(usuario_final_id)
)ENGINE=INNODB;

# GENERANDO RELACIONES
ALTER TABLE ANUNCIO ADD CONSTRAINT ANUNCIO_CATEGORIA_categoria_id FOREIGN KEY (categoria_id) REFERENCES CATEGORIA(id) ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE ANUNCIO ADD CONSTRAINT ANUNCIO_ESTABLECIMIENTO_establecimiento_id FOREIGN KEY (establecimiento_id) REFERENCES ESTABLECIMIENTO(id) ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE ANUNCIO ADD CONSTRAINT ANUNCIO_HISTORIAL_ANUNCIOS_historial_anuncios_id FOREIGN KEY (historial_anuncios_id) REFERENCES HISTORIAL_ANUNCIOS(id) ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE ESTABLECIMIENTO ADD CONSTRAINT ESTABLECIMIENTO_CATEGORIA_categoria_id FOREIGN KEY (categoria_id) REFERENCES CATEGORIA(id) ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE ESTABLECIMIENTO ADD CONSTRAINT ESTABLECIMIENTO_USUARIO_usuario_id FOREIGN KEY (usuario_id) REFERENCES USUARIO(id) ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE PLATILLO ADD CONSTRAINT PLATILLO_CATEGORIA_categoria_id FOREIGN KEY (categoria_id) REFERENCES CATEGORIA(id) ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE PLATILLO ADD CONSTRAINT PLATILLO_ESTABLECIMIENTO_establecimiento_id FOREIGN KEY (establecimiento_id) REFERENCES ESTABLECIMIENTO(id) ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE RESEnA ADD CONSTRAINT RESEnA_PLATILLO_platillo_id FOREIGN KEY (platillo_id) REFERENCES PLATILLO(id) ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE RESEnA ADD CONSTRAINT RESEnA_USUARIO_FINAL_usuario_final_id FOREIGN KEY (usuario_final_id) REFERENCES USUARIO_FINAL(id) ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE HISTORIAL_ANUNCIOS ADD CONSTRAINT HISTORIAL_ANUNCIOS_ESTABLECIMIENTO_establecimiento_id FOREIGN KEY (establecimiento_id) REFERENCES ESTABLECIMIENTO(id) ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE TENDENCIAS ADD CONSTRAINT TENDENCIAS_CATEGORIA_categoria_id FOREIGN KEY (categoria_id) REFERENCES CATEGORIA(id) ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE USUARIO_FINAL ADD CONSTRAINT USUARIO_FINAL_USUARIO_usuario_id FOREIGN KEY (usuario_id) REFERENCES USUARIO(id) ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE FAVORITOS ADD CONSTRAINT FAVORITOS_USUARIO_FINAL_usuario_final_id FOREIGN KEY (usuario_final_id) REFERENCES USUARIO_FINAL(id) ON DELETE NO ACTION ON UPDATE CASCADE;